name: Dev QA workflow

# Controls when the action will run.
on:
  schedule:
    - cron: '5 4 * * 0' # At 21:05 on Sunday

  push:
    branches: [ main, pre-release* ]
  pull_request:
    branches: [ main, pre-release* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      operating-systems: "['ubuntu-latest', 'macos-latest', 'windows-latest']"
      python-versions: "['3.10', '3.11', '3.12']"
      delete-poetry-lock:  true # ${{ github.event_name == 'schedule' }} # the scheduled build tests against newer dependencies
    secrets: inherit
